### ISSUE TITLE
Need some clarifications in regard to `the toIndexableString` method

### ISSUE THREAD

**Issue by kenvunz** [pouchdb/collate#26]
>Warning! This will not work for CouchDB _ids, due to a bug in how Chrome parses URLs. Basically what you will need to do is remove all the \u0000 characters and use some other separator. Assuming you're storing text data and not binary data, \u0001 should be fine:

So does it mean that we cannot use this method to generate the `_id` if we want to do remote syncing to a `CouchDB` server? Or it will work fine with remote CouchDB if we simply replace `\u0000` with \\u0001` as you suggested?

Cheers

**Comment by nolanlawson** [comment]
Yes, that's what it means. You cannot use it if you are syncing with CouchDB, because Chrome misinterprets the `u0000`.

**Comment by nolanlawson** [comment]
I'll update the README.

**Comment by runlevelsix** [comment]
Out of curiosity, why not just make pouch collate use `\u0001` by default instead of `\u0000`? Especially for default interoperability with CouchDB...

**Comment by nolanlawson** [comment]
Legacy reasons. We used the u0000 when we didn't realize it would cause so many problems. :P

**Comment by kristdev** [comment]
Hello can you give an example? if i serialze all properties of a doc, and i want to request only one property? how do i do?

**Comment by nolanlawson** [comment]
Closing because this has been moved into the main PouchDB repo: https://github.com/pouchdb/pouchdb/pull/5476
