### ISSUE TITLE
bower reports v1.1.2 as latest version is 1.2.0

### ISSUE THREAD

**Issue by viskin** [pouchdb/collate#28]
Is the library at v1.2.0 now? If so, there's missing github release, that causes bower to fetch only v1.1.2.
Try

   bower info pouchdb-collate

Prints

  Available versions:
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 0.2.0

**Comment by calvinmetcalf** [comment]
fixed, but I'd recommend trying out npm instead of bower, at this point I see bower as an annoyance I'm occasionally forced to interact with.
