### ISSUE TITLE
make request on document

### ISSUE THREAD

**Issue by kristdev** [pouchdb/collate#29]
Hello, i try to use the plugin, and i have some troubles.
I have succeeded to store documents, this is an  example response: 
```
 {"ok":true,"id":"54demandeur\u00014MALONG BOUGUE\u00014FRANCIS\u00014Ecole supérieure\u00014Cameroon\u00014LITTORAL\u00014DOUALA\u0001323361.44787603671900000357\u0001\u0001","rev":"1-be47f9721bdf049cbacfb52db14f2357"}
```
Now I want to Search in database Documents which a property is a specific value, for example Collection = 'applicants'.

Thanks to see an example of use or research.

**Comment by nolanlawson** [comment]
Sorry for not responding; this project has been moved into the main PouchDB project: https://github.com/pouchdb/pouchdb/pull/5476
